services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Colt-Floral-Crazily9-Paging-Jockstrap
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: